"""Command line helpers: ``wa-agent init`` scaffolds a ready-to-run agent."""

from __future__ import annotations

import argparse
import getpass
import importlib.util
import os
import shutil
import sys
from pathlib import Path

from . import __version__, known_providers

_TEMPLATE = '''"""My WhatsApp AI agent — generated by `wa-agent init`."""

from wa_agent_sdk import WhatsAppAgent, LLMConfig

agent = WhatsAppAgent(
    llm=LLMConfig(
        provider="{provider}",
        model="{model}",{key_line}
    ),
    system_prompt="""{system_prompt}""",
)


@agent.on_message
async def commands(message):
    text = (message.text or "").strip().lower()
    if text in ("/ping", "!ping"):
        return "Pong!"


if __name__ == "__main__":
    agent.run()
'''


def _ask(prompt: str, default: str) -> str:
    suffix = f" [{default}]" if default else ""
    answer = input(f"{prompt}{suffix}: ").strip()
    return answer or default


def cmd_init(args: argparse.Namespace) -> int:
    print("WhatsApp Agent SDK — project wizard\n" + "-" * 40)
    providers = known_providers()
    print(f"Providers: {', '.join(providers)}")
    provider = _ask("Provider", "openai").lower()
    model = _ask("Model", "gpt-4o-mini")
    key = ""
    if provider not in ("ollama", "lmstudio"):
        key = getpass.getpass("API key (blank to read from env var): ").strip()
    session = _ask("Session name", "personal")
    system_prompt = _ask("System prompt", "You are a helpful assistant on WhatsApp.")

    key_line = ""
    if key:
        escaped = key.replace('"', '\\"')
        key_line = f'\n        api_key="{escaped}",'
    else:
        meta_env = {
            "openai": "OPENAI_API_KEY",
            "groq": "GROQ_API_KEY",
            "deepseek": "DEEPSEEK_API_KEY",
            "openrouter": "OPENROUTER_API_KEY",
            "anthropic": "ANTHROPIC_API_KEY",
            "gemini": "GEMINI_API_KEY",
            "together": "TOGETHER_API_KEY",
            "mistral": "MISTRAL_API_KEY",
        }
        env_name = meta_env.get(provider)
        if env_name:
            key_line = f"\n        api_key=os.environ.get(\"{env_name}\"),"

    content = _TEMPLATE.format(
        provider=provider,
        model=model,
        key_line=key_line,
        system_prompt=system_prompt,
        session=session,
    )
    target = Path("my_whatsapp_agent.py")
    if target.exists() and not args.force:
        print(f"\n{target} already exists (use --force to overwrite).")
        return 1
    if "os.environ.get" in content and "import os" not in content:
        content = content.replace('"""', '"""\n\nimport os', 1)
    target.write_text(content, encoding="utf-8")
    print(f"\n✅ Created {target}")
    print("\nNext steps:")
    print(f"  1. python {target.name}")
    print("  2. Scan the QR code with WhatsApp > Linked devices")
    print("  3. Message your own number from another phone — your agent replies!")
    return 0


def _safe_stdout() -> None:
    """Windows consoles default to cp1252; avoid UnicodeEncodeError on glyphs."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure:
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except Exception:  # noqa: BLE001
                pass


def cmd_doctor(_: argparse.Namespace) -> int:
    _safe_stdout()
    checks: list[tuple[str, bool, str]] = []
    checks.append(("Python >= 3.10", sys.version_info >= (3, 10), sys.version.split()[0]))
    node = shutil.which("node")
    checks.append(("Node.js on PATH", node is not None, node or "missing"))
    npm = shutil.which("npm")
    checks.append(("npm on PATH", npm is not None, npm or "missing"))
    for module in ("httpx", "websockets", "pydantic", "qrcode", "PIL", "pypdf", "docx"):
        spec = importlib.util.find_spec(module)
        checks.append((f"python package '{module}'", spec is not None, "ok" if spec else "missing"))
    ok = True
    for name, passed, detail in checks:
        mark = "✔" if passed else "✘"
        print(f"{mark} {name:<28} {detail}")
        ok = ok and passed
    print("\nAll good — run `wa-agent init`." if ok else "\nFix the ✘ items above.")
    return 0 if ok else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="wa-agent",
        description="WhatsApp Agent SDK tooling (Baileys-powered, no Meta verification).",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("init", help="generate a starter agent script")
    init_parser.add_argument("--force", action="store_true", help="overwrite existing file")
    init_parser.set_defaults(func=cmd_init)

    doctor_parser = subparsers.add_parser("doctor", help="check environment readiness")
    doctor_parser.set_defaults(func=cmd_doctor)

    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 0
    result = args.func(args)
    return int(result or 0)


if __name__ == "__main__":
    raise SystemExit(main())
